# Generated by Django 4.0.6 on 2022-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
